# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: InjectFile

      run:  touch resources/ca.key && echo ${{ secrets.CA_KEY }} > resources/ca.key

    - name: Build
      run: make build

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release/benchmark-proxy_linux_amd64
          release/benchmark-proxy_mac_amd64
          release/benchmark-proxy_windows_amd64.exe



